// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBInitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBInitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201912211923365_DBInitialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
